RobotArm_Simulator:
	g++ -o arm_simulator arm_simulator.cpp -lglut -lGLU -lGL

BiologicalEngineering_set3:	
	g++ -o BiologicalEngineering_set3 BiologicalEngineering_set3.cpp -I /usr/include/eigen3/

clean:
	rm -rf arm_simulator
	rm -rf BiologicalEngineering_set3
